[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
src = "src"
out = "out"
libs = ["lib"]
[fuzz]
runs = 1000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 100

[etherscan]
blastSepolia = { key = "${BLASTSCAN_API_KEY}", url = "https://api-sepolia.blastscan.io/api", chain = 168587773 }
blastMainnet = { key = "${BLASTSCAN_API_KEY}", url = "https://api.blastscan.io/api", chain = 81457 }
arbitrumSepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api", chain = 421614 }
arbitrumMainnet = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api", chain = 42161 }
seiMainnet = { key = "${SEITRACE_API_KEY}", url = "https://seitrace.com/pacific-1/api", chain = 1329 }